---
- hosts: localhost
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Docker image build
      command: docker login --username {{ usernamed }} --password {{ passwordd }} docker.io
      
    - name: Print the port of an app
      debug:
        msg: Port is: {{ app_port }}
    
    - name: Docker image build
      command: docker build -t {{ registry_docker }}:{{ build_number }} --build-arg app_port={{ app_port }} {{ workspacej }}
    
    - name: Docker image push
      command: docker push {{ registry_docker }}:{{ build_number }}
      
    - name: Docker local image delete
      command: docker rmi {{ registry_docker }}:{{ build_number }}
      
