---
- hosts: localhost
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Docker image build
      command: docker build {{ refistry_docker }}:{{ build_number }} --build-arg app_port={{ app_port }}
    
    - name: Docker image push
      command: docker push {{ refistry_docker }}:{{ build_number }}
      
    - name: Docker local image delete
      command: docker rmi {{ refistry_docker }}:{{ build_number }}
      
