---
- hosts: localhost
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Docker login
      command: aws configure set --profile default && aws configure set aws_access_key_id {{ access_key }} --profile default && aws_secret_access_key {{ secret_access_key }} --profile default && aws configure set region "us-west-2" --profile default && aws configure set output "text" --profile default
  
    - name: Generate password
      command: aws ecr get-login-password --region us-west-2
      register: aws_pass
      
    - name: Docker login
      command: docker login --username AWS --password {{ aws_pass }} 887303199679.dkr.ecr.us-west-2.amazonaws.com
    
    - name: Docker image build
      command: docker build -t petclinic_repo --build-arg APPD_PORT={{ app_port }} {{ workspacej }}
    
    - name: Docker image tag
      command: docker tag petclinic_repo:latest 887303199679.dkr.ecr.us-west-2.amazonaws.com/petclinic_repo:latest
      
    - name: Docker local image push
      command: docker push 887303199679.dkr.ecr.us-west-2.amazonaws.com/petclinic_repo:latest
