---
- hosts: localhost
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Docker login
      command: docker login --username AWS --password {{ aws_pass }} 887303199679.dkr.ecr.us-west-2.amazonaws.com
    
    - name: Docker image build
      command: docker build -t petclinic_repo --build-arg APPD_PORT={{ app_port }} {{ workspacej }}
    
    - name: Docker image tag
      command: docker tag petclinic_repo:latest 887303199679.dkr.ecr.us-west-2.amazonaws.com/petclinic_repo:latest
      
    - name: Docker local image push
      command: docker push 887303199679.dkr.ecr.us-west-2.amazonaws.com/petclinic_repo:latest
